"""
Source registry for all data providers.
Maps source keys to their configuration and metadata.
"""

SOURCE_REGISTRY = {
    # 1. Dedicated Real Estate Listing Platforms (Market Value)
    "betdelala": {
        "name": "BetDelala",
        "url": "https://betdelala.com",
        "category": "market_listings",
        "valuation_signal": "market_price",
        "scrapability": "high",
    },
    "addislist": {
        "name": "AddisList",
        "url": "https://addislist.com/property",
        "category": "market_listings",
        "valuation_signal": "market_price",
        "scrapability": "high",
    },
    "livingethio": {
        "name": "Living Ethio",
        "url": "https://livingethio.com",
        "category": "market_listings",
        "valuation_signal": "market_price",
        "scrapability": "medium",
    },
    "ethiorealestates": {
        "name": "Ethio Real Estates",
        "url": "https://ethiorealestates.com",
        "category": "market_listings",
        "valuation_signal": "market_price",
        "scrapability": "medium",
    },
    "ethiopiapropertycentre": {
        "name": "Ethiopia Property Centre",
        "url": "https://ethiopiapropertycentre.com",
        "category": "market_listings",
        "valuation_signal": "market_price",
        "scrapability": "high",
    },
    "ethiopiarealty": {
        "name": "Ethiopia Realty",
        "url": "https://ethiopiarealty.com",
        "category": "market_listings",
        "valuation_signal": "market_price",
        "scrapability": "medium",
    },
    "realethio": {
        "name": "Real Ethio",
        "url": "https://realethio.com",
        "category": "market_listings",
        "valuation_signal": "market_price",
        "scrapability": "medium",
    },

    # 2. Tender & Auction Aggregators (Liquidation Value)
    "ethiopiantender": {
        "name": "Ethiopian Tender",
        "url": "https://ethiopiantender.com",
        "category": "auction_aggregators",
        "valuation_signal": "liquidation_value",
        "scrapability": "high",
    },
    "arifchereta": {
        "name": "Arif Chereta",
        "url": "https://arifchereta.com",
        "category": "auction_aggregators",
        "valuation_signal": "liquidation_value",
        "scrapability": "high",
    },
    "reportertenders": {
        "name": "Reporter Tenders",
        "url": "https://reportertenders.com",
        "category": "auction_aggregators",
        "valuation_signal": "liquidation_value",
        "scrapability": "high",
    },
    "habeshatender": {
        "name": "Habesha Tender",
        "url": "https://www.habeshatender.com",
        "category": "auction_aggregators",
        "valuation_signal": "liquidation_value",
        "scrapability": "medium",
    },
    "waliatender": {
        "name": "Walia Tender",
        "url": "https://www.waliatender.com",
        "category": "auction_aggregators",
        "valuation_signal": "liquidation_value",
        "scrapability": "medium",
    },

    # 3. Banking & Institutional Auction Sources (Primary Source)
    "abyssinia": {
        "name": "Bank of Abyssinia",
        "url": "https://www.bankofabyssinia.com",
        "category": "institutional_auctions",
        "valuation_signal": "primary_auction",
        "scrapability": "medium",
    },
    "berhan": {
        "name": "Berhan Bank",
        "url": "https://berhanbanksc.com",
        "category": "institutional_auctions",
        "valuation_signal": "primary_auction",
        "scrapability": "medium",
    },
    "abay": {
        "name": "Abay Bank",
        "url": "https://www.abaybanksc.com",
        "category": "institutional_auctions",
        "valuation_signal": "primary_auction",
        "scrapability": "medium",
    },
    "amhara": {
        "name": "Amhara Bank",
        "url": "https://www.facebook.com/amharabanksc1",
        "category": "institutional_auctions",
        "valuation_signal": "primary_auction",
        "scrapability": "low",
    },
    "dbe": {
        "name": "Development Bank of Ethiopia",
        "url": "https://dbe.com.et",
        "category": "institutional_auctions",
        "valuation_signal": "primary_auction",
        "scrapability": "medium",
    },

    # 4. Specialized Platforms
    "auctionet": {
        "name": "Auction Ethiopia",
        "url": "https://auction.et",
        "category": "specialized_platforms",
        "valuation_signal": "primary_auction",
        "scrapability": "medium",
    },
    "delala": {
        "name": "Delala App",
        "url": "https://delalaapp.com",
        "category": "specialized_platforms",
        "valuation_signal": "market_price",
        "scrapability": "medium",
    },

    # --- NEW SOURCES START ---
    
    # 3. Banking & Institutional Auction Sources (Expanded)
    "cbe": {
        "name": "Commercial Bank of Ethiopia",
        "url": "https://www.combanketh.et",
        "category": "institutional_auctions",
        "valuation_signal": "primary_auction",
        "scrapability": "medium",
    },
    "awash": {
        "name": "Awash Bank",
        "url": "https://awashbank.com",
        "category": "institutional_auctions",
        "valuation_signal": "primary_auction",
        "scrapability": "medium",
    },
    "dashen": {
        "name": "Dashen Bank",
        "url": "https://dashenbanksc.com",
        "category": "institutional_auctions",
        "valuation_signal": "primary_auction",
        "scrapability": "medium",
    },
    "wegagen": {
        "name": "Wegagen Bank",
        "url": "https://www.wegagen.com",
        "category": "institutional_auctions",
        "valuation_signal": "primary_auction",
        "scrapability": "medium",
    },
    "hibret": {
        "name": "Hibret Bank",
        "url": "https://www.hibretbank.com.et",
        "category": "institutional_auctions",
        "valuation_signal": "primary_auction",
        "scrapability": "medium",
    },
    "nib": {
        "name": "Nib International Bank",
        "url": "https://www.nibbanksc.com",
        "category": "institutional_auctions",
        "valuation_signal": "primary_auction",
        "scrapability": "medium",
    },
    "coop": {
        "name": "Cooperative Bank of Oromia",
        "url": "https://coopbankoromia.com.et",
        "category": "institutional_auctions",
        "valuation_signal": "primary_auction",
        "scrapability": "medium",
    },
    "zemen": {
        "name": "Zemen Bank",
        "url": "https://www.zemenbank.com",
        "category": "institutional_auctions",
        "valuation_signal": "primary_auction",
        "scrapability": "medium",
    },
    "enat": {
        "name": "Enat Bank",
        "url": "https://www.enatbanksc.com",
        "category": "institutional_auctions",
        "valuation_signal": "primary_auction",
        "scrapability": "medium",
    },
    "oromia": {
        "name": "Oromia Bank",
        "url": "https://www.oromiabank.com",
        "category": "institutional_auctions",
        "valuation_signal": "primary_auction",
        "scrapability": "medium",
    },
    "bunna": {
        "name": "Bunna Bank",
        "url": "https://bunnabanksc.com",
        "category": "institutional_auctions",
        "valuation_signal": "primary_auction",
        "scrapability": "medium",
    },
    "lion": {
        "name": "Lion International Bank",
        "url": "https://www.anbesabank.com",
        "category": "institutional_auctions",
        "valuation_signal": "primary_auction",
        "scrapability": "medium",
    },
    "global": {
        "name": "Global Bank Ethiopia",
        "url": "https://globalbankethiopia.com",
        "category": "institutional_auctions",
        "valuation_signal": "primary_auction",
        "scrapability": "medium",
    },
    "tsehay": {
        "name": "Tsehay Bank",
        "url": "https://tsehaybank.com.et",
        "category": "institutional_auctions",
        "valuation_signal": "primary_auction",
        "scrapability": "medium",
    },
    "ahadu": {
        "name": "Ahadu Bank",
        "url": "https://ahadubank.com",
        "category": "institutional_auctions",
        "valuation_signal": "primary_auction",
        "scrapability": "medium",
    },
    "hijra": {
        "name": "Hijra Bank",
        "url": "https://hijra-bank.com",
        "category": "institutional_auctions",
        "valuation_signal": "primary_auction",
        "scrapability": "medium",
    },
    "zamzam": {
        "name": "ZamZam Bank",
        "url": "https://zamzambank.com",
        "category": "institutional_auctions",
        "valuation_signal": "primary_auction",
        "scrapability": "medium",
    },
    "siinqee": {
        "name": "Siinqee Bank",
        "url": "https://siinqeebank.com.et",
        "category": "institutional_auctions",
        "valuation_signal": "primary_auction",
        "scrapability": "medium",
    },
    "tsedey": {
        "name": "Tsedey Bank",
        "url": "https://tsedeybank.com.et",
        "category": "institutional_auctions",
        "valuation_signal": "primary_auction",
        "scrapability": "medium",
    },

    # 1. Dedicated Real Estate Listing Platforms (Expanded)
    "myaddis": {
        "name": "MyAddis Property",
        "url": "https://myaddisproperty.com",
        "category": "market_listings",
        "valuation_signal": "market_price",
        "scrapability": "medium",
    },
    "metropolitan": {
        "name": "Metropolitan Real Estate",
        "url": "https://metropolitanaddis.com",
        "category": "market_listings",
        "valuation_signal": "market_price",
        "scrapability": "medium",
    },
    "gift": {
        "name": "Gift Real Estate",
        "url": "https://giftrealestate.com.et",
        "category": "market_listings",
        "valuation_signal": "market_price",
        "scrapability": "medium",
    },
    "sunshine": {
        "name": "Sunshine Investment Group",
        "url": "https://sunshineinvestmentgroup.net",
        "category": "market_listings",
        "valuation_signal": "market_price",
        "scrapability": "medium",
    },
    "ayat": {
        "name": "Ayat Real Estate",
        "url": "https://ayatrealestate.com",
        "category": "market_listings",
        "valuation_signal": "market_price",
        "scrapability": "medium",
    },
    "flintstone": {
        "name": "Flintstone Homes",
        "url": "https://flintstonehomes.com",
        "category": "market_listings",
        "valuation_signal": "market_price",
        "scrapability": "medium",
    },
    "noah": {
        "name": "Noah Real Estate",
        "url": "https://noahrealestate.com",
        "category": "market_listings",
        "valuation_signal": "market_price",
        "scrapability": "medium",
    },
    "ovid": {
        "name": "Ovid Group",
        "url": "https://ovidgroup.com",
        "category": "market_listings",
        "valuation_signal": "market_price",
        "scrapability": "medium",
    },

    # 5. Telegram Channels
    "tg_ethiorealestate": {
        "name": "Ethio Real Estate (Telegram)",
        "url": "https://t.me/ethiorealestate",
        "category": "telegram",
        "valuation_signal": "mixed",
        "scrapability": "medium",
        "channel_id": "ethiorealestate",
    },
    "tg_betoch": {
        "name": "Betoch (Telegram)",
        "url": "https://t.me/betoch",
        "category": "telegram",
        "valuation_signal": "mixed",
        "scrapability": "medium",
        "channel_id": "betoch",
    },
    "tg_addisproperty": {
        "name": "Addis Property (Telegram)",
        "url": "https://t.me/addis_property",
        "category": "telegram",
        "valuation_signal": "mixed",
        "scrapability": "medium",
        "channel_id": "addis_property",
    },
    "tg_delala": {
        "name": "Delala (Telegram)",
        "url": "https://t.me/delala",
        "category": "telegram",
        "valuation_signal": "mixed",
        "scrapability": "medium",
        "channel_id": "delala",
    },
    "tg_sheger_real_estate": {
        "name": "Sheger Real Estate (Telegram)",
        "url": "https://t.me/ShegerRealEstate",
        "category": "telegram",
        "valuation_signal": "mixed",
        "scrapability": "medium",
        "channel_id": "ShegerRealEstate",
    },
    "gohbetoch": {
        "name": "Goh Betoch Bank",
        "url": "https://www.gohbetochbank.com",
        "category": "institutional_auctions",
        "valuation_signal": "primary_auction",
        "scrapability": "medium",
    },
    "shabelle": {
        "name": "Shabelle Bank",
        "url": "https://shabellebank.com",
        "category": "institutional_auctions",
        "valuation_signal": "primary_auction",
        "scrapability": "medium",
    },
    "gadaa": {
        "name": "Gadaa Bank",
        "url": "https://gadaabank.com.et",
        "category": "institutional_auctions",
        "valuation_signal": "primary_auction",
        "scrapability": "medium",
    },
    "ramis": {
        "name": "Ramis Bank",
        "url": "https://ramisbank.com",
        "category": "institutional_auctions",
        "valuation_signal": "primary_auction",
        "scrapability": "medium",
    },
    "addis_intl": {
        "name": "Addis International Bank",
        "url": "https://addisbanksc.com",
        "category": "institutional_auctions",
        "valuation_signal": "primary_auction",
        "scrapability": "medium",
    },
    "sidama": {
        "name": "Sidama Bank",
        "url": "https://sidamabanksc.com",
        "category": "institutional_auctions",
        "valuation_signal": "primary_auction",
        "scrapability": "medium",
    },
    "awach_sacco": {
        "name": "Awach SACCO",
        "url": "https://awachsacco.com",
        "category": "institutional_auctions",
        "valuation_signal": "primary_auction",
        "scrapability": "low",
    },
    "oromia_sacco": {
        "name": "Oromia Artisans SACCO",
        "url": "https://www.oassco.com",
        "category": "institutional_auctions",
        "valuation_signal": "primary_auction",
        "scrapability": "low",
    },
    "hameran": {
        "name": "Hameran Real Estate",
        "url": "https://hameranrealestate.com",
        "category": "market_listings",
        "valuation_signal": "market_price",
        "scrapability": "medium",
    },
    "qefira": {
        "name": "Qefira Property",
        "url": "https://www.qefira.com/houses",
        "category": "market_listings",
        "valuation_signal": "market_price",
        "scrapability": "medium",
        "selectors": {
            "card": ".listing-card",
            "title": ".listing-title",
            "price": ".price",
        }
    },
    "jiiji": {
        "name": "Jiiji Ethiopia",
        "url": "https://jiiji.com.et/houses-apartments-for-sale",
        "category": "market_listings",
        "valuation_signal": "market_price",
        "scrapability": "medium",
    },
    "delala_et": {
        "name": "Delala.et",
        "url": "https://delala.et",
        "category": "market_listings",
        "valuation_signal": "market_price",
        "scrapability": "medium",
    },
    "engocha": {
        "name": "Engocha",
        "url": "https://engocha.com",
        "category": "market_listings",
        "valuation_signal": "market_price",
        "scrapability": "medium",
    },
    "afroaddis": {
        "name": "AfroAddis",
        "url": "https://afroaddis.com",
        "category": "market_listings",
        "valuation_signal": "market_price",
        "scrapability": "medium",
    },
    "ethiotenders": {
        "name": "EthioTenders",
        "url": "https://ethiotenders.com",
        "category": "auction_aggregators",
        "valuation_signal": "liquidation_value",
        "scrapability": "medium",
    },
    "merkato": {
        "name": "2merkato Tenders",
        "url": "https://www.2merkato.com/tenders",
        "category": "auction_aggregators",
        "valuation_signal": "liquidation_value",
        "scrapability": "medium",
    },
    "ezega": {
        "name": "Ezega Real Estate",
        "url": "https://www.ezega.com/RealEstate",
        "category": "market_listings",
        "valuation_signal": "market_price",
        "scrapability": "medium",
    },
    "hellodelala": {
        "name": "HelloDelala",
        "url": "https://hellodelala.com",
        "category": "market_listings",
        "valuation_signal": "market_price",
        "scrapability": "medium",
    },
    "sheger_property": {
        "name": "Sheger Property",
        "url": "https://shegerproperty.com",
        "category": "market_listings",
        "valuation_signal": "market_price",
        "scrapability": "medium",
    },
    "abenet": {
        "name": "Abenet Real Estate",
        "url": "http://abenetrealestate.com",
        "category": "market_listings",
        "valuation_signal": "market_price",
        "scrapability": "medium",
    },
    "ccd": {
        "name": "Country Club Developers",
        "url": "https://ccdethiopia.com",
        "category": "market_listings",
        "valuation_signal": "market_price",
        "scrapability": "medium",
    },
    "varnero": {
        "name": "Varnero Real Estate",
        "url": "https://varneroit.com",
        "category": "market_listings",
        "valuation_signal": "market_price",
        "scrapability": "medium",
    },
    "eagle_hills": {
        "name": "Eagle Hills La Gare",
        "url": "https://www.eaglehills.com/ethiopia",
        "category": "market_listings",
        "valuation_signal": "market_price",
        "scrapability": "medium",
    },
    "poly_lotus": {
        "name": "Poly Lotus International",
        "url": "http://www.polylotus.com.et",
        "category": "market_listings",
        "valuation_signal": "market_price",
        "scrapability": "medium",
    },
    "mela": {
        "name": "Mela Real Estate",
        "url": "https://melarealestate.com",
        "category": "market_listings",
        "valuation_signal": "market_price",
        "scrapability": "medium",
    },
    "z_realestate": {
        "name": "Z Real Estate",
        "url": "https://zrealestateethiopia.com",
        "category": "market_listings",
        "valuation_signal": "market_price",
        "scrapability": "medium",
    },
    "ethio_home": {
        "name": "Ethio Home",
        "url": "https://ethiohome.com",
        "category": "market_listings",
        "valuation_signal": "market_price",
        "scrapability": "medium",
    },
    "addis_home": {
        "name": "Addis Home",
        "url": "https://addishome.com",
        "category": "market_listings",
        "valuation_signal": "market_price",
        "scrapability": "medium",
    },
    "f_property": {
        "name": "F-Property Ethiopia",
        "url": "https://fpropertyethiopia.com",
        "category": "market_listings",
        "valuation_signal": "market_price",
        "scrapability": "medium",
    },
    "tg_ethiotender": {
        "name": "EthioTender (Telegram)",
        "url": "https://t.me/ethiotender",
        "category": "telegram",
        "valuation_signal": "liquidation_value",
        "scrapability": "medium",
        "channel_id": "ethiotender",
    },
    "tg_arifchereta": {
        "name": "Arif Chereta (Telegram)",
        "url": "https://t.me/arifchereta",
        "category": "telegram",
        "valuation_signal": "liquidation_value",
        "scrapability": "medium",
        "channel_id": "arifchereta",
    },
}

MARKET_PRICE_SOURCE_KEYS = [k for k, v in SOURCE_REGISTRY.items() if v["valuation_signal"] == "market_price"]
AUCTION_VALUE_SOURCE_KEYS = [k for k, v in SOURCE_REGISTRY.items() if v["valuation_signal"] in ["liquidation_value", "primary_auction"]]

def iter_sources(category=None):
    """Iterate through sources, optionally filtered by category."""
    for key, config in SOURCE_REGISTRY.items():
        if category and config["category"] != category:
            continue
        yield key, config
